config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Commontator::Engine => '/commontator'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :charges
  resources :courses do
    resources :lessons
  end

  resources :sessions
  resources :users

  get 'my_dashboard' => 'dashboards#my_dashboard', as: :user_dashboard

  get 'sign_in' => 'sessions#new', as: :sign_in
  delete 'sign_out' => 'sessions#destroy', as: :sign_out
  get 'sign_up' => 'users#new', as: :sign_up
  get 'lesson_complete' => 'lessons#user_completed', as: :lesson_completed

  get 'apply_discount_code' => 'charges#apply_discount_code', as: :apply_discount_code
  post 'calculate_discount_price' => 'charges#calculate_discount_price', as: :calculate_discount_price
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_paper_trail
  acts_as_commontable

  belongs_to :course, touch: true, dependent: :destroy
  has_many :completions

  validates :name, :description, :video_url, :notes, :thumbnail_url, :duration,
    :lesson_number, :course_id, presence: true

  validates_numericality_of :duration, :lesson_number

  validate :lesson_number_can_not_duplicate_another_in_same_course

  def lesson_number_can_not_duplicate_another_in_same_course
    lessons  = Lesson.where(course_id: course_id)
    if lessons.where(course_id: course_id, lesson_number: lesson_number).present?
      errors.add(:lesson_number, 'You have already used this lesson number for
                 this course.')
    end
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  expose(:lesson, attributes: :lesson_params)
  expose(:course) { Course.friendly.find(params[:course_id]) }
  expose(:completions) { current_user.completions}
  expose(:user)

  before_action :require_login, except: :index
  before_action :require_admin, except: [:show, :index, :user_completed]
  before_action :require_active_subscription, only: :show

  layout "lesson"

  def show
    self.course = Course.friendly.find(params[:course_id])
    commontator_thread_show(lesson)
  end

  def index
    self.course = Course.friendly.find(params[:course_id])
  end

  def update
    self.course = Course.friendly.find(params[:course_id])
    if lesson.update_attributes(lesson_params)
      redirect_to course_lessons_path(course)
    else
      render :edit
    end
  end

  def create
    self.course = Course.friendly.find(params[:course_id])
    lesson.course = course
    if lesson.save
      redirect_to course_lessons_path(course)
    else
      render :new
    end
  end

  def user_completed
    if user_completion = Completion.where(user_id: current_user.id,
      lesson_id: params[:lesson_id]).last
      user_completion.destroy
    else
      Completion.create!(user_id: current_user.id, lesson_id: params[:lesson_id],
        completed: true, course_id: params[:course_id])
    end
  end

  def require_active_subscription
    unless session[:course_access] = course.id
      redirect_to new_charge_path(course_id: course.id) unless Charge.where(
        "access_expiration_date > ? AND user_id = ? AND course_id = ?", Date.today.to_s,
        current_user.id, course.id).present?
      session[:course_access] = course.id
    end
  end

  private

  def lesson_params
    params.require(:lesson).permit(:name, :description, :notes, :video_url,
      :free, :duration, :lesson_number)
  end

end

app/helpers/lessons_helper.rb
module LessonsHelper

  def user_has_access?
    Charge.where(
      "access_expiration_date > ? AND user_id = ? AND course_id = ?", Date.today.to_s,
      current_user.id, course.id).present?
  end

  def user_completion(lesson)
    if current_user
      if completions = lesson.completions.where(user_id: current_user.id)
        completions.present? && completions.last.completed?
        @completion = completions.last
      end
    end
  end

  def lesson_completed?
    if lesson_completion = Completion.where(user_id: current_user.id,
      lesson_id: lesson.id, completed: true).last
      lesson_completion
    end
  end

  def lesson_progress_finished?(lesson)
    @completion = Completion.where(user_id: current_user.id,
      lesson_id: lesson.id, completed: true).last
    @completion.present?
  end

  def next_lesson
    if next_lesson = Lesson.find_by_lesson_number(lesson.lesson_number + 1)
      @next_lesson = course_lesson_path(course, next_lesson)
    end
  end

  def previous_lesson
    if previous_lesson = Lesson.find_by_lesson_number(lesson.lesson_number - 1)
        @previous_lesson = course_lesson_path(course, previous_lesson)
    end
  end

end

app/views/lessons/_lesson.html.haml
- if user_has_access?
  - cache lesson do
    .card
      .card-image
        %img{:alt => "", :src => lesson.thumbnail_url}
      .card-header
        = link_to lesson.name, course_lesson_path(course, lesson)
        / = link_to 'Edit', edit_course_lesson_path(course, lesson)
      .card-copy
        %p
          = lesson.description.truncate(310).truncate(310)
        %p.right
          = link_to 'Start Lesson', course_lesson_path(course, lesson), class: 'btn'
      .card-stats
        %ul
          %li
            - cache @completion do
              - if user_completion(lesson)
                Yes
              - else
                No
            %span Completed?
          %li
            = lesson.duration
            %span Minutes
          %li
            Easy
            %span Difficulty
- elsif lesson.free?
  - cache lesson do
    .card
      .ribbon-wrapper
        .ribbon FREE
      .card-image
        %img{:alt => "", :src => lesson.thumbnail_url}
      .card-header
        = link_to lesson.name, course_lesson_path(course, lesson)
      .card-copy
        %p
          = lesson.description.truncate(310)
        %p.right
          = link_to 'Start Lesson', course_lesson_path(course, lesson), class: 'btn'
      .card-stats
        %ul
          %li
            - if user_completion(lesson)
              Yes
            - else
              No
            %span Completed?
          %li
            = lesson.duration
            %span Minutes
          %li
            Easy
            %span Difficulty
- else
  - cache lesson do
    .card
      .card-image
        %img{:alt => "", :src => lesson.thumbnail_url}
      .card-header
        = lesson.name
      .card-copy
        %p.center
          = link_to 'Get Access To This Lesson', new_charge_path(course_id: course.id), class: 'btn yellow-btn', id: "get_access#{lesson.id}"
      .card-stats
        %ul
          %li
            - if user_completion(lesson)
              Yes
            - else
              No
            %span Completed?
          %li
            = lesson.duration
            %span Minutes
          %li
            Easy
            %span Difficulty

app/views/lessons/edit.html.haml
= form_for lesson, url: course_lesson_path, method: :put do |f|
  = f.text_field :name, placeholder: 'Name'
  = f.text_area :description, placeholder: 'Description'
  .countdown.right
    350
  %br
  = f.text_area :notes, placeholder: 'Notes'
  %br
  = f.text_field :video_url, placeholder: 'Vimeo Video ID'
  = f.label :free, 'Free?'
  = f.check_box :free
  = f.label :duration, 'Minutes'
  = f.select(:duration, options_for_select(1..60))
  = f.url_field :thumbnail_url, placeholder: 'Vimeo Thumbnail URL'
  = f.submit

:javascript
  function updateCountdown() {
    // 350 is the max message length
    var remaining = 350 - jQuery('#lesson_description').val().length;
    jQuery('.countdown').text(remaining + ' characters remaining.');
  }

  jQuery(document).ready(function($) {
    updateCountdown();
    $('#lesson_description').change(updateCountdown);
    $('#lesson_description').keyup(updateCountdown);
  });

app/views/lessons/index.html.haml
.intro-text
  %h1 Lessons
  - if admin?
    = link_to 'Add Lesson', new_course_lesson_path(course)
.cards
  - cache course.lessons do
    = render course.lessons.order(:name)

app/views/lessons/new.html.haml
%h1
  Add a new lesson
%h2
  = course.name

= form_for lesson, url: course_lessons_path do |f|
  = f.text_field :name, placeholder: 'Name'
  = f.text_area :description, placeholder: 'Description'
  .countdown.right
    350
  %br
  = f.text_area :notes, placeholder: 'Notes'
  %br
  = f.text_field :video_url, placeholder: 'Vimeo Video ID'
  = f.label :free, 'Free?'
  = f.check_box :free
  = f.label :duration, 'Minutes'
  = f.select(:duration, options_for_select(1..60))
  = f.url_field :thumbnail_url, placeholder: 'Vimeo Thumbnail URL'
  = f.label :lesson_number
  = f.number_field :lesson_number
  = f.submit

:javascript
  function updateCountdown() {
    // 350 is the max message length
    var remaining = 350 - jQuery('#lesson_description').val().length;
    jQuery('.countdown').text(remaining + ' characters remaining.');
  }

  jQuery(document).ready(function($) {
    updateCountdown();
    $('#lesson_description').change(updateCountdown);
    $('#lesson_description').keyup(updateCountdown);
  });

app/views/lessons/show.html.haml
- content_for :head do
  = stylesheet_link_tag 'pygments'
.intro-text
  %h2
    = lesson.name
.clear
.intro-wrapper#intro
  %section.intro-content
    .well
      %p
        = lesson.description
      .right
        = link_to "Awesome! Let's start the lesson!", '#', id: 'start-lesson', class: 'data-no-turbolink'

#lesson-content
  %section
    .video-wrapper
      %iframe{:allowfullscreen => "", :frameborder => "0", :height => "506", :mozallowfullscreen => "", :src => "//player.vimeo.com/video/#{lesson.video_url}", :webkitallowfullscreen => "", :width => "900"}
.bigtop-pad
.make-space-left
  - course_progress
  .progress-bar-indication
    %span.meter{style: "width: #{@percentage}"}
  %p.center
    Course Progress
.completion-section.data-no-turbolink
  - if current_course_customer?(course)
    - if lesson_completed?
      #lesson-incomplete
        = link_to 'Mark this lesson completed', lesson_completed_path(lesson_id: lesson.id, course_id: course.id), remote: true, class: 'btn'
      #lesson-complete
        = link_to 'Mark this lesson incomplete', lesson_completed_path(lesson_id: lesson.id, course_id: course.id), remote: true, class: 'btn'
    - else
      #lesson-complete
        = link_to 'Mark this lesson completed', lesson_completed_path(lesson_id: lesson.id, course_id: course.id), remote: true, class: 'btn'
      #lesson-incomplete
        = link_to 'Mark this lesson incomplete', lesson_completed_path(lesson_id: lesson.id, course_id: course.id), remote: true, class: 'btn'
    %br
    .right.data-no-turbolink
      - if next_lesson
        = link_to 'Go to Next Lesson', @next_lesson
      - else
        Finished Course!
      - if previous_lesson
        %br
        = link_to 'Go to Previous Lesson', @previous_lesson
  - else
    = link_to 'Buy this Course to continue', new_charge_path(course_id: course.id)
.clear
#lesson-notes-and-discussion
  %ul.accordion-tabs
    %li.tab-header-and-content
      %a.is-active.tab-link{:href => "#"} Lesson Notes
      .tab-content
        = markdown lesson.notes
    %li.tab-header-and-content
      %a.tab-link{:href => "#"} Discussion
      .tab-content
        %p
          = commontator_thread(lesson)