config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Commontator::Engine => '/commontator'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :charges
  resources :courses do
    resources :lessons
  end

  resources :sessions
  resources :users

  get 'my_dashboard' => 'dashboards#my_dashboard', as: :user_dashboard

  get 'sign_in' => 'sessions#new', as: :sign_in
  delete 'sign_out' => 'sessions#destroy', as: :sign_out
  get 'sign_up' => 'users#new', as: :sign_up
  get 'lesson_complete' => 'lessons#user_completed', as: :lesson_completed

  get 'apply_discount_code' => 'charges#apply_discount_code', as: :apply_discount_code
  post 'calculate_discount_price' => 'charges#calculate_discount_price', as: :calculate_discount_price
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  has_paper_trail
  include AASM

  belongs_to :course
  belongs_to :user
  belongs_to :discount_code

  validates :guid, uniqueness: true
  validates :user_id, :course_id, :amount, presence: true
  validates :amount, numericality: { greater_then: 49 }

  before_create :populate_guid

  aasm column: 'state' do
    state :pending, intital: true
    state :processing
    state :finished
    state :errored

    event :process, after: :charge_card do
      transitions from: :pending, to: :processing
    end

    event :finish do
      transitions from: :processing, to: :finished
    end

    event :fail do
      transitions from: :processing, to: :errored
    end
  end

  def active?
    access_expiration_date > Date.today
  end

  private

  def populate_guid
    self.guid = SecureRandom.uuid()
  end

  def charge_card
    begin
      stripe_charge = create_stripe_charge
      update_charge(stripe_charge)
      self.finish!
    rescue Stripe::StripeError => e
      self.update_attributes(error: e.message)
      self.fail!
    end
  end

  def create_stripe_charge
    Stripe::Charge.create(amount: self.amount, currency: "usd",
      customer: self.customer_id, description: self.course.name,
      card: self.default_card)
  end

  def update_charge(stripe_charge)
    balance = Stripe::BalanceTransaction.retrieve(stripe_charge.balance_transaction)
    self.update(stripe_id: stripe_charge.id,
      card_expiration: Date.new(stripe_charge.card.exp_year, stripe_charge.card.exp_month, 1),
      fee_amount: balance.fee)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  expose(:user) { current_user }
  expose(:course) { Course.friendly.find(params[:course_id]) }
  expose(:charge, attributes: :charges_params)
  expose(:charges) { Charge.all.order("created_at DESC") }

  before_action :require_admin, except: [:new, :show, :create,
                                         :apply_discount_code, :calculate_discount_price]
  before_action :require_login

  def new
    session[:course_id] = params[:course_id]
    if session[:discount_code_id]
      @price = course.calculate_final_discounted_price(session[:discount_code_id])
    else
      @price = course.price
    end
  end

  def show
    self.charge = Charge.find_by_guid(params[:id])
    unless current_user.admin?
      redirect_to root_path unless charge.user == current_user
    end
  end

  def create
    session[:discount_code_id] = nil
    self.course = Course.find(session[:course_id])
    if charge = create_customer_and_charge(params, course)
      StripeRunnerJob.perform_now charge.guid
      flash[:success] = 'Thanks for your purchase!'
      redirect_to user_dashboard_path
    else
      charge_error
    end
  end

  def create_customer_and_charge(params, course)
    if customer = create_customer(params)
      create_charge(params, customer, course)
    end
  end

  def create_customer(params)
    Stripe::Customer.create(email: current_user.email, card: params["stripeToken"])
  end

  def create_charge(params, customer, course)
    course.charges.create(
      amount: params[:final_sale_price],
      user_id: current_user.id,
      customer_id: customer.id,
      course_id: course.id,
      default_card: customer.default_card,
      discount_code_id: params[:discount_code_id],
      course_price: course.price,
      access_expiration_date: Date.today + 1.year
    )
  end

  def charge_error
    flash.now[:alert] = "We're sorry, it look like we had a connection issue!
          Your card was NOT charged. Please try again!"
    render :new
  end

  def apply_discount_code
  end

  def calculate_discount_price
    self.course = Course.find(session[:course_id])
    if discount_code = DiscountCode.find_by(discount_code: params[:discount_code])
      if discount_code.not_expired_or_cancelled?
        apply_discount(discount_code, course)
      else
        expired_code(course)
      end
    else
      code_not_found(course)
    end
  end

  def apply_discount(discount_code, course)
    session[:discount_code_id] = discount_code.id
    flash[:success] = 'Discount applied!'
    redirect_to new_charge_path(course_id: course.id)
  end

  def expired_code(course)
    flash[:error] = 'That discount code has expired!'
    redirect_to new_charge_path(course_id: course.id)
  end

  def code_not_found(course)
    flash[:error] = 'Sorry, but that code was not found.'
    redirect_to new_charge_path(course_id: course.id)
  end

  private

  def charges_params
    params.require(:charge).permit(:course_id, :user_id, :amount, :customer_id,
                                   :access_expiration_date, :default_card)
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_charge.html.haml
%tr
  %td
    = link_to charge.user.display_name, user_path(charge.user)
  %td
    = charge.created_at.strftime('%d %b %Y')
  %td
    = charge.course.name
  %td
    = charge.access_expiration_date.strftime('%d %b %Y')
  %td
    = link_to charge.guid, charge_path(charge.guid)
  %td
    = number_to_currency(charge.amount/100, precision: 0)
  %td
    = number_to_currency(charge.fee_amount/100, precision: 2)
  %td
    = charge.state
  %td
    = charge.discount_code.discount_code if charge.discount_code

app/views/charges/_discount_form.html.haml
#sign-up-form
  %fieldset
    = form_tag calculate_discount_price_path do
      .field
        = text_field_tag :discount_code
      .actions
        = submit_tag 'Apply Code'
      .actions
        = link_to 'Nevermind', '#'

app/views/charges/apply_discount_code.js.erb
$('#discount-code').hide().after('<%= j render("discount_form") %>');

app/views/charges/create.html.haml
%h1
  You did it! Congratulations

app/views/charges/index.html.haml
.intro-text
  %h1
    Transactions

%table.table-borders
  %thead
    %tr
      %th
        Customer
      %th
        Date
      %th
        Course
      %th
        Access Expires
      %th
        Guid
      %th
        Amount Charged
      %th
        Stripe Fee
      %th
        Status
      %th
        Discount Users?
  %tbody
    = render charges

app/views/charges/new.html.haml
.intro-text
  %h1
    It's go time!
  %h4
    You're seconds away from starting your goal to learn how to program!
  %h5
    = course.name
  %br
  - if session[:discount_code_id]
    %h2
      %del
        = number_to_currency(course.price/100, precision: 0)
  %h2
    = number_to_currency(@price/100, precision: 0)

  = form_tag charges_path do
    - if @discount
      = hidden_field_tag :discount_code_id, session[:discount_code_id]
    = hidden_field_tag :final_sale_price, @price
    %script.stripe-button{"data-amount" => "#{@price.to_i}", "data-image" => "https://eace9f72bdbdb48b3a1c-84b89a0ff7c53bcaecc8d06d99783f99.ssl.cf1.rackcdn.com/images/everybody_codes_logo_150px.png", "data-allow-remember-me" => "false", "data-label" => "Order Now", "data-email" => "#{current_user.email}", "data-name" => "Everybody Code!", "data-description" => "#{course.name}", "data-key" => Rails.configuration.stripe[:publishable_key], :src => "https://checkout.stripe.com/checkout.js"}
  - unless session[:discount_code_id]
    .lesson-header
      = link_to 'Use a discount code', apply_discount_code_path, remote: true, id: 'discount-code'
%p.type
  Unlimited access to this course for 1 year.
.checkmark-features
  %ul.fa-ul
    %li
      %i.fa-li.fa.fa-1x.fa-check-square>
      %p
        Stream HD lessons on any device
    %li
      %i.fa-li.fa.fa-1x.fa-check-square>
      %p
        Access to your instructor through email
    %li
      %i.fa-li.fa.fa-1x.fa-check-square>
      %p
        Participation in lesson discussions
    %li
      %i.fa-li.fa.fa-1x.fa-check-square>
      %p
        Course e-textbook with notes and examples

app/views/charges/show.html.haml
.intro-text
  %h1
    Transaction Details
- if admin?
  %h5
    Status: #{charge.state}
  %h5
    User
  %ul
    %li
      = link_to charge.user.display_name, user_path(charge.user)
    %li
      = mail_to charge.user.email
    %li
      Stripe Customer ID: #{charge.customer_id}
  %hr
%h5
  Purchase
%ul
  %li
    Purchase Date: #{charge.created_at.strftime('%d %b %Y')}
  %li
    Purchase Amount: #{number_to_currency(charge.amount/100, precision: 0)}
  - if admin?
    %li
      Stripe Fee: #{number_to_currency(charge.fee_amount/100, precision: 2)}
    %li
      Original Course Price: #{number_to_currency(charge.course_price/100, precision: 2)}
    - if charge.discount_code
      %li
        Discount Used: #{charge.discount_code.discount_code}
%h5
  Course
%ul
  %li
    = charge.course.name
  %li
    Access expires on #{charge.access_expiration_date.strftime('%d %b %Y')}