config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Commontator::Engine => '/commontator'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :charges
  resources :courses do
    resources :lessons
  end

  resources :sessions
  resources :users

  get 'my_dashboard' => 'dashboards#my_dashboard', as: :user_dashboard

  get 'sign_in' => 'sessions#new', as: :sign_in
  delete 'sign_out' => 'sessions#destroy', as: :sign_out
  get 'sign_up' => 'users#new', as: :sign_up
  get 'lesson_complete' => 'lessons#user_completed', as: :lesson_completed

  get 'apply_discount_code' => 'charges#apply_discount_code', as: :apply_discount_code
  post 'calculate_discount_price' => 'charges#calculate_discount_price', as: :calculate_discount_price
end

app/views/layouts/_flashes.html.haml
- flash.each do | key, value|
  = content_tag :div, value, class: "flash flash-#{key}"

app/views/layouts/_footer.html.haml
%footer.footer-2
  .footer-logo
    %img{:alt => "Logo image", :src => "https://eace9f72bdbdb48b3a1c-84b89a0ff7c53bcaecc8d06d99783f99.ssl.cf1.rackcdn.com/images/everybody_codes_logo_150px.png"}
  %ul
    %li
      &copy; 2014 Everybody Code!
  .footer-secondary-links
    %ul
      %li
        = link_to 'Terms of Use', page_path('terms')
      %li
        = link_to 'Privacy', page_path('privacy')
    %ul.footer-social
      %li
        %a{:href => "javascript:void(0)"}
          %i.fa.fa-youtube.fa-2x
      %li
        %a{:href => "javascript:void(0)"}
          %i.fa.fa-twitter.fa-2x
      %li
        %a{:href => "javascript:void(0)"}
          %i.fa.fa-facebook.fa-2x

app/views/layouts/_head.html.haml
%title Everybody Code!
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
= csrf_meta_tags
%meta{content: "width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1", name: "viewport"}
%link{:href => "http://fonts.googleapis.com/css?family=Lusitana:400,700", :rel => "stylesheet", :type => "text/css"}
%link{:href => "http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic", :rel => "stylesheet", :type => "text/css"}
  %link{:href => "http://fonts.googleapis.com/css?family=Merriweather+Sans:400,300,300italic,400italic,700italic,700,800,800italic", :rel => "stylesheet", :type => "text/css"}
= yield :head

app/views/layouts/_header.html.haml
%header.centered-navigation
  .centered-navigation-wrapper
    %a.mobile-logo{href: root_path}
      %img{alt: "Logo image", :src => "https://eace9f72bdbdb48b3a1c-84b89a0ff7c53bcaecc8d06d99783f99.ssl.cf1.rackcdn.com/images/everybody_codes_logo_150px.png"}
    %a.centered-navigation-menu-button{href: ""} MENU
    %ul.centered-navigation-menu
      %li.nav-link.logo
        %a.logo{href: root_path}
          %img{alt: "Logo image", :src => "https://eace9f72bdbdb48b3a1c-84b89a0ff7c53bcaecc8d06d99783f99.ssl.cf1.rackcdn.com/images/everybody_codes_logo_150px.png"}
      %li.nav-link
        = link_to 'Courses', courses_path
      %li.nav-link
        = link_to 'About', page_path('about')
      %li.nav-link
        %a{href: "javascript:void(0)"} Help
      %li.nav-link
        = link_to 'Blog', 'http://everybodycode.com'
      - if logged_in?
        %li.nav-link
          = link_to 'Dashboard', user_dashboard_path
        %li.nav-link
          - if logged_in?
            = link_to 'Sign out', sign_out_path, method: :delete
        - if admin?
          %li.nav-link.more
            %a{href: "javascript:void(0)"} Admin
            %ul.submenu
              %li
                = link_to 'Transactions', charges_path
              %li
                = link_to 'Users', users_path
      - else
        %li.nav-link
          = link_to t('.sign_in'), sign_in_path
  %p.right
    Happy #{Date.today.strftime("%A")}!

app/views/layouts/_lesson_header.html.haml
%header.centered-navigation
  .centered-navigation-wrapper
    %a.mobile-logo{href: root_path}
      %img{alt: "Logo image", :src => "https://eace9f72bdbdb48b3a1c-84b89a0ff7c53bcaecc8d06d99783f99.ssl.cf1.rackcdn.com/images/everybody_codes_logo_150px.png"}
    %a.centered-navigation-menu-button{href: ""} Lesson Menu
    %ul.centered-navigation-menu
      %li.nav-link.logo
        %a.logo{href: root_path}
          %img{alt: "Logo image", :src => "https://eace9f72bdbdb48b3a1c-84b89a0ff7c53bcaecc8d06d99783f99.ssl.cf1.rackcdn.com/images/everybody_codes_logo_150px.png"}
      %li.nav-link
        = link_to 'Lessons', course_lessons_path(course)
      %li.nav-link
        = link_to 'Dashboard', user_dashboard_path
      %li.nav-link
        %a{href: "javascript:void(0)"} Help
      %li.nav-link
        - if logged_in?
          = link_to 'Sign out', sign_out_path, method: :delete
        - else
          = link_to t('.sign_in'), sign_in_path
.name.right
  %h5
    = course.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render 'layouts/head'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %body
    .wrapper-for-content-outside-of-footer
      = render 'layouts/header'
      = render 'layouts/flashes'
      .outer-wrapper
        = yield
    = render 'layouts/footer'

app/views/layouts/lesson.html.haml
!!!
%html
  %head
    = render 'layouts/head'
  %body
    .wrapper-for-content-outside-of-footer
      = render 'layouts/lesson_header'
      = render 'layouts/flashes'
      .outer-wrapper
        = yield
    = render 'layouts/footer'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true